package vlasovspringbanksystem.utils;

public enum TypeOfOperation {
    CREATE_DEPOSIT_ACC, CREATE_CREDIT_ACC, REFILL_ACC, INTRABANK_PAYMENT,
    FOREIGN_BANK_PAYMENT, INCOMING_PAYMENT, DEPOSIT_INTEREST, CREDIT_INTEREST
}
